// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xDh8v3ERwJDgqwoBci5X6vsxzqgW2qk',
    appId: '1:234837708660:web:989066aae1d6e029b2a621',
    messagingSenderId: '234837708660',
    projectId: 'pocketmemory-c2dd8',
    authDomain: 'pocketmemory-c2dd8.firebaseapp.com',
    storageBucket: 'pocketmemory-c2dd8.appspot.com',
    measurementId: 'G-R77Q69Y3RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHEf8u0RFvw7QwtMK0H9gwHgwYSBTQF8',
    appId: '1:234837708660:android:5dac3fdc235f8988b2a621',
    messagingSenderId: '234837708660',
    projectId: 'pocketmemory-c2dd8',
    storageBucket: 'pocketmemory-c2dd8.appspot.com',
  );
}
